### ISSUE TITLE
Question: Does moveit2 support the python interface and it is just not documented?

### ISSUE THREAD

**Issue by marc-wittwer** [ros-planning/moveit2#1268]
I am currently starting a 6 month research project that involves robot arm manipulation. I am quite new to ROS and moveit.

I am reading through all the moveit documentation to figure out if I should use moveit 1 or moveit 2. 

I am very familiar with python and not so much with c++ and thus I am hesitant to go with moveit 2. Python tutorials are missing in the moveit 2 documentation at the moment. However, I saw that the moveit2 repo has the `moveit_commander` folder.

**Does the `moveit_commander` interface already work or should i go with C++?**

Also I saw the https://github.com/AndrejOrsula/pymoveit2 repo which has limited capabilities. Or should I use the pymoveit2 library?

Also the rest of my setup would work well with ROS 2 (Unity Robotics Hub, Gazebo Ignition).

I think that I will only require the basic moveit functionalities e.g. motion planning, gripping, avoiding obstacles, environmental constraints.

Can someone with more moveit experience give me a recommendation as to which moveit version I should select?

**Comment by vatanaksoytezer** [comment]
Hello Marc,

> **Does the `moveit_commander` interface already work or should i go with C++?**

`moveit_commander` has not been ported to ROS2. You can interface moveit2 with python in message / action level using something similar to Andrej's work you linked. The official recommended way to interface with moveit2 is using C++, typically through MoveItCpp or MoveGroupInterface.

I don't see you would have big troubles if you are only going to use basic functionalities either in moveit or moveit2. We have been using moveit2 in many real life projects by now. There is a comparison post that has been made in last August, [here](https://moveit.ros.org/ros2/moveit/2021/06/08/moveit-vs-moveit2.html). Since then we have MTC and hybrid planning working in MoveIt2.

Hope this clarifies things a little bit for you. Please let us know if you have any further questions

**Comment by nbbrooks** [comment]
Hi Marc - good news! We will be working on MoveIt 2 Python bindings as part of the [Google Summer of Code program](https://moveit.ros.org/events/moveit/mentor/google/2022/05/20/2022-google-summer-of-code-students.html)!

**Comment by marioesteban11** [comment]
Hi everyone. 

`Hi Marc - good news! We will be working on MoveIt 2 Python bindings as part of the [Google Summer of Code program](https://moveit.ros.org/events/moveit/mentor/google/2022/05/20/2022-google-summer-of-code-students.html)!`

I was wondering if this is finished.

Thanks in advanced

**Comment by vatanaksoytezer** [comment]
@marioesteban11 I think it's pretty close to finish line. You canfollow https://github.com/ros-planning/moveit2/issues/1279 and https://github.com/ros-planning/moveit2/pull/1546 for updates
