### ISSUE TITLE
[MSA] joints used by multiple groups are duplicated in ros2_control.xacro

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/moveit2#1390]
### Description

Some robots have multiple groups with similar joints (for instance: arm, arm_with_torso). When this is configured in the MSA, the joints that are present in both groups show up twice in the ros2_control.xacro

### Your environment
* ROS Distro: humble
* OS Version: Ubuntu 22.04
* Source build of feature/msa

**Comment by mikeferguson** [comment]
FYI @DLu

**Comment by DLu** [comment]
There is [a bug where those joints are added to the `joint_names_` vector twice](https://github.com/ros-planning/moveit2/blob/6ab20361242cc81dc06913f3ac52486d31c11f5e/moveit_setup_assistant/moveit_setup_controllers/src/control_xacro_config.cpp#L128) but because the generated interfaces are [`unordered_map` based](https://github.com/ros-planning/moveit2/blob/6ab20361242cc81dc06913f3ac52486d31c11f5e/moveit_setup_assistant/moveit_setup_controllers/include/moveit_setup_controllers/control_xacro_config.hpp#L191), I'm currently not seeing the duplicated values in `ros2_control.xacro`. 

Are you using the MoveIt config [checked  in here](https://github.com/mikeferguson/ubr_reloaded/tree/ros2/ubr1_moveit), @mikeferguson ?

**Comment by mikeferguson** [comment]
That is the latest export (23 hours ago from now) and if you see https://github.com/mikeferguson/ubr_reloaded/blob/ros2/ubr1_moveit/config/ubr1.ros2_control.xacro it has duplicated data

**Comment by mikeferguson** [comment]
The issue appears to be that we do the export by looping over the joint_names_ (which has duplicates): https://github.com/ros-planning/moveit2/blob/6ab20361242cc81dc06913f3ac52486d31c11f5e/moveit_setup_assistant/moveit_setup_controllers/src/control_xacro_config.cpp#L233 - PR incoming
