### ISSUE TITLE
Error finding moveit_ros_perception

### ISSUE THREAD

**Issue by hagenfal** [ros-planning/moveit2#1685]
Hello, 
I'm new using ROS and Moveit.
I have a problem with moveit_ros_perception and I don't know how to solve it.
I've updated my Linux from 20.04 to 22.04 and from ROS Foxy to ROS Humble.
Is the moveit_ros_perception package still in moveit2?
Or do I have to install it extra?

` CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "Findmoveit_ros_perception.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "moveit_ros_perception", but CMake did not find one.

  Could not find a package configuration file provided by
  "moveit_ros_perception" with any of the following names:

    moveit_ros_perceptionConfig.cmake
    moveit_ros_perception-config.cmake

  Add the installation prefix of "moveit_ros_perception" to CMAKE_PREFIX_PATH
  or set "moveit_ros_perception_DIR" to a directory containing one of the
  above files.  If "moveit_ros_perception" provides a separate development
  package or SDK, be sure it has been installed.`

**Comment by henningkayser** [comment]
Please try installing `moveit_ros_perception` manually, using

```
sudo apt install ros-humble-moveit-ros-perception
```

Also, if you project depends on `moveit_ros_perception`, it should be listed in your `package.xml` so that rosdep can pick it up and install it.

The reason you ran into this is probably because the meta-package `moveit_ros` [doesn't list the perception package](https://github.com/ros-planning/moveit2/blob/foxy/moveit_ros/moveit_ros/package.xml#L23) which should be fixed as well.
