### ISSUE TITLE
Can't launch setup assistant

### ISSUE THREAD

**Issue by moar55** [ros-planning/moveit2#219]
### Description

Overview of your issue here.
I am unable to launch the setup assistant. After I build the project with `colcon build` I attempt to run or launch the virtual assistant but the setup assistant package is not recognized.
### Your environment
* ROS Distro: Eloquent
* OS Version: e.g. Ubuntu 18.04
* Source or Binary build?
 source
* If binary, which release version?
* If source, which branch?
master
### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.
### Expected behaviour
The setup assistant should launch.
### Actual behaviour
It doesn't and gives me an error that the setup_assistant package doesn't exist 
### Backtrace or Console output
When running `ros2 pkg list` these are the only moveit2 packages i receive:
```
moveit_core
moveit_kinematics
moveit_msgs
moveit_planners_ompl
moveit_resources
moveit_ros_occupancy_map_monitor
moveit_ros_planning
moveit_ros_planning_interface
moveit_ros_visualization
moveit_simple_controller_manager
```
`ros2 moveit_setup_assistant setup_assistant` returns error that the package is not found:
https://gist.github.com/moar55/94bc0b63e9f171e35a47323aa95fc6a9.

**Comment by JafarAbdi** [comment]
Hi @moar55,

As you can see in the [migration progress sheet](https://docs.google.com/spreadsheets/d/1aPb3hNP213iPHQIYgcnCYh9cGFUlZmi_06E_9iTSsOI/edit#gid=0) moveit_setup_assistant isn't ported yet, but you could use the generated package from MoveIt's moveit_setup_assistant with some minor modification to make work with MoveIt2 [example](https://github.com/JafarAbdi/panda_moveit_config/commit/7f08a3d4e4448729d73c2e06fd1470c51262a65a)

> When running `ros2 pkg list` these are the only moveit2 packages i receive:

It's because we ignore this package when building with colcon [see](https://github.com/ros-planning/moveit2/blob/master/moveit_setup_assistant/COLCON_IGNORE)
