### ISSUE TITLE
Do we plan to support sync with main for humble branch?

### ISSUE THREAD

**Issue by CalvinRoboForce** [ros-planning/moveit2#2356]
**Is your feature request related to a problem? Please describe.**
To keep humble branch up-to-dated with latest features, do we have the plan to sync with the `main` branch in `humble`? Thanks!

**Describe the solution you'd like**
Support sync with the `main` branch in `humble`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by henningkayser** [comment]
@CalvinRoboForce we are maintaining humble as stable branch, meaning that we don't backport features right away in order to provide stable long-term support with API stability. Syncing with main is not possible because of that, but we are aiming to backport backwards-compatible fixes and improvements. Also, keep in mind that we keep `main` compatible with the humble distro (enforced by CI), so you can always install get the latest features if you need them for development.
Do you have any specific features you think should be backported anyway?
Please close this issue if this answers your question.
