### ISSUE TITLE
Add label to readme

### ISSUE THREAD

**Issue by shraddha761** [ros-planning/moveit2#2495]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/ros-planning/moveit2/assets/106100728/2b99042c-de47-43d6-bab9-5456eb5efd41)

**Describe the solution you'd like**
There should be more label to readme which make it look more attractive.

**Describe alternatives you've considered**

**Additional context**
Assign this issue to me

**Comment by sjahr** [comment]
@shraddha761 Thanks for opening the issue, please open a PR with additional label's you'd propose to add. I'll close this issue since I don't think we need to track this. If you're interested in other work: Feel free to pick up one of the other open issues e.g. addressing one of the [open first timer issues](https://github.com/ros-planning/moveit2/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)
