### ISSUE TITLE
Plan&Execution Fails although it finishes the Planning an Execution

### ISSUE THREAD

**Issue by Hadi-Hajieghrary** [ros-planning/moveit2#2577]
### Description

Although the planning and execution is seemingly done properly in the RVIZ, it messages out Failed with the following messages:

[gzserver-1] [INFO] [1701793049.770259550] [mh180_120_arm_controller]: Got request to cancel goal
[move_group-7] [INFO] [1701793049.770485263] [moveit_ros.trajectory_execution_manager]: Completed trajectory execution with status TIMED_OUT ...
[move_group-7] [INFO] [1701793049.775329227] [moveit_move_group_default_capabilities.move_action_capability]: TIMED_OUT
[rviz2-9] [INFO] [1701793049.775708508] [move_group_interface]: Plan and Execute request aborted
[rviz2-9] [ERROR] [1701793049.776137702] [move_group_interface]: MoveGroupInterface::move() failed or timeout reached
[move_group-7] [INFO] [1701793049.815903056] [moveit.simple_controller_manager.follow_joint_trajectory_controller_handle]: Controller '/mh180_120_arm_controller' successfully finished

### Your environment
* ROS Distro: HUMBLE
* OS Version: Ubuntu 22.04
* Source or Binary build?
* If binary, which release version?
* If source, which branch? HEAD detached at 459b810ab
* Which RMW (Fast DDS or Cyclone DDS)? Cyclone.

### Steps to reproduce
Tell us how to reproduce this issue. Attempt to provide a working demo, perhaps using Docker.

### Expected behavior
Plan and Finish Execution, return success.

### Actual behavior
Plan and Finish Execution, but return failure! (see Attached 
[Screencast from 12-05-2023 11:26:19 AM.webm](https://github.com/ros-planning/moveit2/assets/40810998/11bc69cf-9f0f-4fc0-b181-7391c642fe2f)
)

**Comment by henningkayser** [comment]
This typically happens if the joint trajectory controller fails to halt the robot at the goal state within the defined tolerances. They can be configured as described in the [ros2_control documentation](https://control.ros.org/master/doc/ros2_controllers/joint_trajectory_controller/doc/userdoc.html#using-joint-trajectory-controller-s). Especially, when running hardware or simulation (here Gazebo apparently), it's common to run into this issue. Just bump up the tolerances.
