### ISSUE TITLE
Request for moveit_setup_assistant support

### ISSUE THREAD

**Issue by JaehyunShim** [ros-planning/moveit2#388]
Hi, 

It seems the MoveIt dev team hasn't started working on the future moveit_setup_assistant support yet. I would like to ask about the plan for it. If the team is too busy to work on it now, I am interested in contributing to it since I am going to work on something similar to it (building a setup assistant) in the future.

Thanks, 
Jaehyun

**Comment by henningkayser** [comment]
We've started planning for future MSA support (see #313 and attached milestone issues). Because of the fundamental changes to the ROS launch infrastructure, we decided to do a redesign of the MoveIt config package and with that a refactoring of the MSA. A complete straight port doesn't make too much sense, unfortunately, but you are very welcome to add to the discussion or contribute. If you are still willing and have capacity to put work into MSA, please let me know and we can sync up to coordinate this effort.

**Comment by JaehyunShim** [comment]
THanks! I will close this issue and will look forward to the new setup assistant.
