### ISSUE TITLE
Finish Windows port

### ISSUE THREAD

**Issue by ooeygui** [ros-planning/moveit2#504]
This Feature request is to finish the Windows port as started in https://github.com/ros-planning/moveit2/pull/238.

@lilustga and I (@ooeygui) will be working on this; this issue is to capture that workstream for tracking purposes.

**Comment by Ace314159** [comment]
@ooeygui I have a [fork of MoveIt2](https://github.com/Ace314159/moveit2) that builds and properly runs for my team's usage. I didn't create a PR to merge it in since there was already an existing PR for a windows port, and I wanted to get the fixes for the other repos merged in first.

I'd love to combine our efforts and help with finishing the port.

**Comment by ooeygui** [comment]
@Ace314159 Awesome! Would love to connect and discuss - can you add me to your network on linkedin? https://www.linkedin.com/in/louamadio/

**Comment by Ace314159** [comment]
@ooeygui I've sent a request.

**Comment by Ace314159** [comment]
I have created #530 which address this.

**Comment by lilustga** [comment]
First Foxy release to include the Windows port fixes. https://github.com/ros-planning/moveit2/releases/tag/2.3.0

Now testing it on Windows!

Galactic testing soon as well
