### ISSUE TITLE
Update adapt_and_plan() method of planning_request_adapter::PlanningRequestAdapter

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/moveit2#610]
The method is meant to be overridden. It has this signature:

```
  bool adaptAndPlan(const PlannerFn& planner, const planning_scene::PlanningSceneConstPtr& planning_scene,
                    const planning_interface::MotionPlanRequest& req, planning_interface::MotionPlanResponse& res,
                    std::vector<std::size_t>& /*added_path_index*/) const override
```

If the planner arg were not const, we wouldn't need to instantiate the "planner" every single time. (For example TOTG or the new Ruckig smoother.)

Originally proposed [here](https://github.com/ros-planning/moveit2/pull/571#discussion_r686447993).

**Comment by henningkayser** [comment]
I don't think adapters should be able to actually interfere with the planner instance so const really makes a lot of sense here. The adapter's scope is limited to access the planning response. Also, were is the planner being instantiated repeatedly? If you mean the adapter algorithm or other plugin members, there is nothing stopping us from making them const members. If there is data that should be kept between multiple plugin calls, that would be very suspicious for a bug. Consecutive calls should be handled independently and should not reuse the same data since we are getting isolated motion plan results. If there is still some internal state to be kept (say, for a trajectory cache), then there is still the option to use a mutable.
